# docker-compose.yml
version: '3'
services:
  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - HOST=${HOST}
      - DATABASE=${DATABASE}
      - USER=${DB_USER}
      - PASSWORD=${PASSWORD}
      - DB_URL=postgresql://${DB_USER}:${PASSWORD}@${HOST}/${DATABASE}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: