# docker-compose.yml
version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - HOST=postgres
      - DATABASE=${DATABASE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DB_URL=postgresql://${USER}:${PASSWORD}@postgres/${DATABASE}
    depends_on:
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:13
    ports:
      - "5433:5432"  # Changed host port to 5433
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: